# Generated by Django 4.2.9 on 2024-01-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairservice_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NailServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nairservice_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerbook',
            name='services',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='customerbook',
            name='hairservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.hairservices'),
        ),
        migrations.AddField(
            model_name='customerbook',
            name='nailservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.nailservices'),
        ),
        migrations.AddField(
            model_name='package',
            name='hairservice',
            field=models.ManyToManyField(related_name='customersbook', to='salon.hairservices'),
        ),
        migrations.AddField(
            model_name='package',
            name='nailservice',
            field=models.ManyToManyField(related_name='customersbook', to='salon.nailservices'),
        ),
    ]
