# Generated by Django 4.2.9 on 2024-01-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_hairservices_nailservices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nailservices',
            old_name='nairservice_name',
            new_name='nailservice_name',
        ),
    ]
