# Generated by Django 4.2.9 on 2024-01-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_rename_nairservice_name_nailservices_nailservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairservices',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nailservices',
            name='description',
        ),
    ]
