# Generated by Django 4.2.9 on 2024-01-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_remove_hairservices_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairCuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircuts_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customerbook',
            old_name='date_appoint',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='customerbook',
            name='date_appointed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerbook',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customerbook',
            name='haircut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.haircuts'),
        ),
        migrations.AddField(
            model_name='package',
            name='haircut',
            field=models.ManyToManyField(related_name='customersbook', to='salon.haircuts'),
        ),
    ]
