# Generated by Django 4.2.9 on 2024-01-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_customerbook_address_alter_customerbook_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbook',
            name='haircut',
        ),
        migrations.RemoveField(
            model_name='customerbook',
            name='hairservice',
        ),
        migrations.RemoveField(
            model_name='customerbook',
            name='nailservice',
        ),
        migrations.RemoveField(
            model_name='customerbook',
            name='package',
        ),
        migrations.AddField(
            model_name='customerbook',
            name='time_appointed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerbook',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbook',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
