# Generated by Django 4.2.9 on 2024-02-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_remove_customerbook_haircut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbook',
            old_name='date_appointed',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='customerbook',
            old_name='time_appointed',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='package',
            name='haircut',
        ),
        migrations.AddField(
            model_name='customerbook',
            name='customer_picture',
            field=models.ImageField(blank=True, upload_to='customer_picture/'),
        ),
        migrations.AddField(
            model_name='customerbook',
            name='hair_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.hairservices'),
        ),
        migrations.AddField(
            model_name='customerbook',
            name='nails_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.nailservices'),
        ),
        migrations.AlterField(
            model_name='customerbook',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='package',
            name='hairservice',
        ),
        migrations.RemoveField(
            model_name='package',
            name='nailservice',
        ),
        migrations.DeleteModel(
            name='HairCuts',
        ),
        migrations.AddField(
            model_name='package',
            name='hairservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.hairservices'),
        ),
        migrations.AddField(
            model_name='package',
            name='nailservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.nailservices'),
        ),
    ]
